/**
 * This file is autogenerated by ETH Mobile.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from '@/utils/eth-mobile';

const deployedContracts = {
  31337: {
    LuckyGuess: {
      address: '0x700b6a60ce7eaaea56f065753d8dcb9653dbad35',
      abi: [
        {
          type: 'receive',
          stateMutability: 'payable'
        },
        {
          type: 'function',
          name: 'MAX_BET',
          inputs: [],
          outputs: [
            {
              name: '',
              type: 'uint256',
              internalType: 'uint256'
            }
          ],
          stateMutability: 'view'
        },
        {
          type: 'function',
          name: 'MAX_NUMBER',
          inputs: [],
          outputs: [
            {
              name: '',
              type: 'uint256',
              internalType: 'uint256'
            }
          ],
          stateMutability: 'view'
        },
        {
          type: 'function',
          name: 'betsPerAddress',
          inputs: [
            {
              name: '',
              type: 'address',
              internalType: 'address'
            }
          ],
          outputs: [
            {
              name: '',
              type: 'uint256',
              internalType: 'uint256'
            }
          ],
          stateMutability: 'view'
        },
        {
          type: 'function',
          name: 'guess',
          inputs: [
            {
              name: '_guess',
              type: 'uint8',
              internalType: 'uint8'
            }
          ],
          outputs: [],
          stateMutability: 'payable'
        },
        {
          type: 'function',
          name: 'totalBets',
          inputs: [],
          outputs: [
            {
              name: '',
              type: 'uint256',
              internalType: 'uint256'
            }
          ],
          stateMutability: 'view'
        },
        {
          type: 'event',
          name: 'Played',
          inputs: [
            {
              name: 'player',
              type: 'address',
              indexed: true,
              internalType: 'address'
            },
            {
              name: 'guess',
              type: 'uint8',
              indexed: false,
              internalType: 'uint8'
            },
            {
              name: 'result',
              type: 'uint8',
              indexed: false,
              internalType: 'uint8'
            },
            {
              name: 'bet',
              type: 'uint256',
              indexed: false,
              internalType: 'uint256'
            },
            {
              name: 'won',
              type: 'bool',
              indexed: false,
              internalType: 'bool'
            }
          ],
          anonymous: false
        },
        {
          type: 'error',
          name: 'InsufficientContractBalance',
          inputs: []
        },
        {
          type: 'error',
          name: 'InvalidBet',
          inputs: []
        },
        {
          type: 'error',
          name: 'InvalidGuess',
          inputs: []
        },
        {
          type: 'error',
          name: 'TransferFailed',
          inputs: []
        }
      ],
      inheritedFunctions: {},
      deploymentFile: 'run-1773777378928.json',
      deploymentScript: 'Deploy.s.sol'
    }
  }
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
