/**
 * This file is autogenerated by ETH Mobile.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "../src/utils/eth-mobile/contract";

const deployedContracts = {
  31337: {
    LuckyGuess: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [],
          name: "InsufficientContractBalance",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidBet",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidGuess",
          type: "error",
        },
        {
          inputs: [],
          name: "TransferFailed",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "player",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "guess",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "result",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "bet",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "won",
              type: "bool",
            },
          ],
          name: "Played",
          type: "event",
        },
        {
          inputs: [],
          name: "MAX_BET",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_NUMBER",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "betsPerAddress",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "_guess",
              type: "uint8",
            },
          ],
          name: "guess",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalBets",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
