/**
 * This file is autogenerated by ETH Mobile.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from '../src/utils/eth-mobile/contract';

const deployedContracts = {
  31337: {
    LuckyGuess: {
      address: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
      abi: [
        {
          inputs: [],
          name: 'InsufficientContractBalance',
          type: 'error'
        },
        {
          inputs: [],
          name: 'InvalidBet',
          type: 'error'
        },
        {
          inputs: [],
          name: 'InvalidGuess',
          type: 'error'
        },
        {
          inputs: [],
          name: 'TransferFailed',
          type: 'error'
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'address',
              name: 'player',
              type: 'address'
            },
            {
              indexed: false,
              internalType: 'uint8',
              name: 'guess',
              type: 'uint8'
            },
            {
              indexed: false,
              internalType: 'uint8',
              name: 'result',
              type: 'uint8'
            },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'bet',
              type: 'uint256'
            },
            {
              indexed: false,
              internalType: 'bool',
              name: 'won',
              type: 'bool'
            }
          ],
          name: 'Played',
          type: 'event'
        },
        {
          inputs: [],
          name: 'MAX_BET',
          outputs: [
            {
              internalType: 'uint256',
              name: '',
              type: 'uint256'
            }
          ],
          stateMutability: 'view',
          type: 'function'
        },
        {
          inputs: [],
          name: 'MAX_NUMBER',
          outputs: [
            {
              internalType: 'uint256',
              name: '',
              type: 'uint256'
            }
          ],
          stateMutability: 'view',
          type: 'function'
        },
        {
          inputs: [
            {
              internalType: 'address',
              name: '',
              type: 'address'
            }
          ],
          name: 'betsPerAddress',
          outputs: [
            {
              internalType: 'uint256',
              name: '',
              type: 'uint256'
            }
          ],
          stateMutability: 'view',
          type: 'function'
        },
        {
          inputs: [
            {
              internalType: 'uint8',
              name: '_guess',
              type: 'uint8'
            }
          ],
          name: 'guess',
          outputs: [],
          stateMutability: 'payable',
          type: 'function'
        },
        {
          inputs: [],
          name: 'totalBets',
          outputs: [
            {
              internalType: 'uint256',
              name: '',
              type: 'uint256'
            }
          ],
          stateMutability: 'view',
          type: 'function'
        },
        {
          stateMutability: 'payable',
          type: 'receive'
        }
      ],
      inheritedFunctions: {}
    },
    MultiReturnDemo: {
      address: '0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0',
      abi: [
        {
          inputs: [],
          stateMutability: 'nonpayable',
          type: 'constructor'
        },
        {
          inputs: [
            {
              internalType: 'address',
              name: '',
              type: 'address'
            }
          ],
          name: 'balanceOf',
          outputs: [
            {
              internalType: 'uint256',
              name: '',
              type: 'uint256'
            }
          ],
          stateMutability: 'view',
          type: 'function'
        },
        {
          inputs: [
            {
              internalType: 'address',
              name: 'account',
              type: 'address'
            }
          ],
          name: 'getAccountInfo',
          outputs: [
            {
              internalType: 'uint256',
              name: 'balance',
              type: 'uint256'
            },
            {
              internalType: 'bool',
              name: 'active',
              type: 'bool'
            }
          ],
          stateMutability: 'view',
          type: 'function'
        },
        {
          inputs: [
            {
              internalType: 'address',
              name: 'account',
              type: 'address'
            }
          ],
          name: 'getAccountInfoStruct',
          outputs: [
            {
              components: [
                {
                  internalType: 'uint256',
                  name: 'balance',
                  type: 'uint256'
                },
                {
                  internalType: 'bool',
                  name: 'isActive',
                  type: 'bool'
                },
                {
                  internalType: 'address',
                  name: 'account',
                  type: 'address'
                }
              ],
              internalType: 'struct MultiReturnDemo.AccountInfo',
              name: 'info',
              type: 'tuple'
            }
          ],
          stateMutability: 'view',
          type: 'function'
        },
        {
          inputs: [],
          name: 'getStats',
          outputs: [
            {
              internalType: 'uint256',
              name: 'count',
              type: 'uint256'
            },
            {
              internalType: 'bool',
              name: 'isPaused',
              type: 'bool'
            },
            {
              internalType: 'address',
              name: 'ownerAddress',
              type: 'address'
            }
          ],
          stateMutability: 'view',
          type: 'function'
        },
        {
          inputs: [],
          name: 'increment',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function'
        },
        {
          inputs: [
            {
              internalType: 'address',
              name: '',
              type: 'address'
            }
          ],
          name: 'isWhitelisted',
          outputs: [
            {
              internalType: 'bool',
              name: '',
              type: 'bool'
            }
          ],
          stateMutability: 'view',
          type: 'function'
        },
        {
          inputs: [],
          name: 'owner',
          outputs: [
            {
              internalType: 'address',
              name: '',
              type: 'address'
            }
          ],
          stateMutability: 'view',
          type: 'function'
        },
        {
          inputs: [],
          name: 'paused',
          outputs: [
            {
              internalType: 'bool',
              name: '',
              type: 'bool'
            }
          ],
          stateMutability: 'view',
          type: 'function'
        },
        {
          inputs: [
            {
              internalType: 'address',
              name: 'account',
              type: 'address'
            },
            {
              internalType: 'uint256',
              name: 'amount',
              type: 'uint256'
            }
          ],
          name: 'setBalance',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function'
        },
        {
          inputs: [
            {
              internalType: 'bool',
              name: '_paused',
              type: 'bool'
            }
          ],
          name: 'setPaused',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function'
        },
        {
          inputs: [
            {
              internalType: 'address',
              name: 'account',
              type: 'address'
            },
            {
              internalType: 'bool',
              name: 'status',
              type: 'bool'
            }
          ],
          name: 'setWhitelisted',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function'
        },
        {
          inputs: [],
          name: 'totalCount',
          outputs: [
            {
              internalType: 'uint256',
              name: '',
              type: 'uint256'
            }
          ],
          stateMutability: 'view',
          type: 'function'
        }
      ],
      inheritedFunctions: {}
    }
  }
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
